name: Dennis Schubert
markdown: redcarpet
highlighter: pygments
permalink: /blog/:year/:month/:day/:title.html

exclude:
  - .*
  - Gemfile
  - Gemfile.lock

redcarpet:
  extensions:
    - autolink
    - fenced_code_blocks
    - strikethrough

sass:
  sass_dir: css
  style: nested
  deploy_style: nested
