name: Dennis Schubert
markdown: redcarpet
highlighter: pygments
permalink: /blog/:year/:month/:day/:title.html
main_base_url: http://schub.io

collections:
  - projects

exclude:
  - .*
  - Gemfile
  - Gemfile.lock

redcarpet:
  extensions:
    - autolink
    - fenced_code_blocks
    - strikethrough
    - superscript

sass:
  sass_dir: css
  style: nested
  deploy_style: nested
