source 'http://rubygems.org'

gem 'mysql2', '0.2.6'
gem 'rails', '3.0.3'
gem 'rake', '0.8.7'
gem 'bundler'
gem 'haml', '3.1.2'
gem 'sass', '3.1.4'
gem 'jammit', '0.5.4'
gem 'jquery-rails'
gem 'RedCloth', '~> 4.2.7'
gem 'coderay', '~> 0.9.8'
gem 'devise', '~> 1.4.2'
gem 'settingslogic', '2.0.6'
gem 'passenger'
